services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db      
    volumes:
      - images:/images
      - logs:/logs
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - images:/images
    networks:
      - app-network
      
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: images_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network      

volumes:
  images:
  logs:
  db_data:

networks:
  app-network:
    driver: bridge
