services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - images:/images
      - logs:/logs
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - images:/images
    networks:
      - app-network

volumes:
  images:
  logs:

networks:
  app-network:
    driver: bridge
